// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewxgsseelkjyxkfxbsqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3eGdzc2VlbGtqeXhrZnhic3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MDU2ODQsImV4cCI6MjA1NzE4MTY4NH0.VGeJaccGIE_QOZA7fEW7_3Zv5EZrmhqZa3U-9eX2A6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);